- name: Create snapshot
## If the entire inventory snapshot is not intended, limit the guest snapshots based 
## upon the 'Limit' variable in the job template.
  hosts: all
  gather_facts: False
  vars:
   timestamp: "{{lookup('pipe', 'date +%Y%m%d%H%M%S')}}"
  connection: local
  tasks:
    - name: Take Snapshot of Guest VM
      vmware_guest_snapshot:
        validate_certs: false

## Ensure to use your VMWare Cloud Credential (VMware vCenter) with the Job template. 
## Currently the job template requires a Machine Credential, create a blank Machine Credential
## to use in addition to the VMWare Cloud Credential.
        username: "{{ ansible_env.VMWARE_USER }}"
        password: "{{ ansible_env.VMWARE_PASSWORD }}"
        hostname: "{{ ansible_env.VMWARE_HOST }}"
        datacenter: MPCOMPS
        
## For each Host in the Inventory, retrieves Name and UUID from the Hosts Variables.
        uuid: "{{ config.uuid }}"
        state: present
        snapshot_name: 'Snapshot_{{ timestamp }}'
        description: Automated snapshot from Ansible.
      delegate_to: localhost
